Question_Statements = {
    1: {"question_statement": [["Het is makkelijk mij persoonlijk te leren kennen op zakelijke of onbekende sociale bijeenkomsten."],
                        ["Het is niet zo makkelijk mij persoonlijk te leren kennen op zakelijke of onbekende sociale bijeenkomsten."]],
        "styles": ("O,S")},
    2: {"question_statement": [["Ik richt mijn gesprekken vaak op onderwerpen en taken die voor de hand liggen, onderwerpgericht."],
                        ["Ik richt mijn gesprekken voornamelijk op mijn persoonlijke ervaringen; ik kan afdwalen."]],
        "styles": ("S,O")},
    3: {"question_statement": [["Ik voel me niet gemakkelijk in groepsgesprekken."],
                        ["Ik voel me gemakkelijk in groepsgesprekken."]],
        "styles": ("I,D")},
    4: {"question_statement": [["Ik volg alle regels letterlijk op."],
                        ["Ik interpreteer de algemene geest van de regels."]],
        "styles": ("I,D")},
    5: {"question_statement": [["Ik maak de meeste beslissingen op basis van doelen, feiten en bewijzen."],
                        ["Ik maak beslissingen op basis van gevoel, ervaringen en relaties."]],
        "styles": ("S,O")},
    6: {"question_statement": [["Ik maak weinig gebruik van mijn non-verbale communicatie en mijn stem om de nadruk ergens op te leggen."],
                        ["Ik gebruik regelmatig mijn non-verbale communicatie en stem om ergens nadruk op te leggen."]],
        "styles": ("I,D")},
    7: {"question_statement": [["Ik gebruik meer empathische uitspraken als 'ik voel'."],
                        ["Ik gebruik meer feitelijke uitspraken als 'uit mijn bronnen blijkt'"]],
        "styles": ("D,I")},
    8: {"question_statement": [["Ik heb een grote natuurlijke neiging naar het gebruik van mijn mimiek en lichaamstaal tijdens spreken en luisteren."],
                        ["Ik heb niet echt de neiging gebruik te maken van mijn mimiek en lichaamstaal tijdens het spreken en luisteren."]],
        "styles": ("O,S")},
    9: {"question_statement": [["Ik houd mijn persoonlijke gevoelens voor mijzelf, ik deel ze alleen als het nodig is."],
                        ["Ik deel vrij en open mijn persoonlijke gevoelens met anderen."]],
        "styles": ("S,O")},
    10: {"question_statement": [["Ik laat minder enthousiasme zien dan anderen."],
                         ["Ik laat meer enthousiasme zien dan anderen."]],
         "styles": ("S,O")},
    11: {"question_statement": [["Op sociale gelegenheden stel ik mijzelf voor."],
                         ["Op sociale gelegenheden wacht ik liever af tot een ander zich voorstelt."]],
         "styles": ("D,I")},
    12: {"question_statement": [["Ik ben flexibel in hoe anderen met mijn tijd omgaan."],
                         ["Ik ben gedisciplineerd in hoe anderen met mijn tijd omgaan."]],
         "styles": ("O,S")},
    13: {"question_statement": [["Ik houd het liefst vast aan mijn agenda."],
                         ["Ik ga het liefst mee met de omstandigheden."]],
         "styles": ("S,O")},
    14: {"question_statement": [["Ik toon assertief gedrag."],
                         ["Ik toon gereserveerd gedrag."]],
         "styles": ("D,I")},
    15: {"question_statement": [["Ik geef graag mijn eigen mening over dingen."],
                         ["Ik ben gereserveerd in het geven van mijn eigen mening."]],
         "styles": ("D,I")},
    16: {"question_statement": [["Ik neem het liefst spontane en impulsieve beslissingen."],
                         ["Ik maak weloverwogen keuzes."]],
         "styles": ("D,I")},
    17: {"question_statement": [["Ik werk het liefst onafhankelijk of ik stel eisen aan de omstandigheden rond een samenwerkingsverband."],
                         ["Ik werk het liefst samen of ik ben een onderdeel van de relaties."]],
         "styles": ("S,O")},
    18: {"question_statement": [["Van nature benader ik risico’s en verandering langzaam en met voorzichtigheid."],
                         ["Van nature benader ik risico's en verandering snel en spontaan."]],
         "styles": ("I,D")}
}